[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["dev@theradius.xyz"]
homepage = "https://theradius.xyz"
repository = "https://github.com/radiusxyz/radius-sdk-rs"

[workspace]
resolver = "2"
members = [
    "crates/context",
    "crates/json-rpc/json-rpc-client",
    "crates/json-rpc/json-rpc-server",
    "crates/kvstore/kvstore",
    "crates/kvstore/kvstore-macros",
    "crates/liveness/liveness-radius",
    "crates/signature",
    "crates/validation-service",
    "radius-sdk",
]

[workspace.dependencies]
primitives = { path = "./crates/primitives" }
signature = { path = "./crates/signature" }

ethers-core = "2.0"
sha3 = "0.10"
k256 = "0.13"
itoa = "1"
ed25519-dalek = "2.1"
alloy = { version = "1.0.23", default-features = false }
async-trait = "0.1.88"
chrono = "0.4"
bincode = "1.3"
const-hex = "1.12"
futures = "0.3"
pin-project = "1.1"
rand = "0.8"
rand_core = "0.6"
thiserror = "2.0.12"
serde = { version = "1.0.197", default-features = false }
serde_json = { version = "1.0", default-features = false }
tokio = { version = "1.37.0", features = ["full"] }
clap = { version = "4.4.7", features = ["derive"] }
proc-macro2 = { version = "1.0.86", default-features = false }
quote = { version = "1.0.37", default-features = false }
syn = { version = "2.0.79", default-features = false }
